# Generated by Django 4.0 on 2024-06-13 03:25

from django.db import migrations, models
import toprofile_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('toprofile_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to=toprofile_api.models.AdminAppearance.upload_to)),
                ('icon', models.ImageField(null=True, upload_to=toprofile_api.models.AdminAppearance.upload_to)),
                ('background', models.ImageField(null=True, upload_to=toprofile_api.models.AdminAppearance.upload_to)),
            ],
        ),
    ]
