# Generated by Django 4.0 on 2024-07-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toprofile_api', '0003_device_mostviewpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
