# Generated by Django 4.0 on 2024-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toprofile_api', '0005_mostviewpage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostviewpage',
            name='name',
        ),
        migrations.AddField(
            model_name='mostviewpage',
            name='count',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mostviewpage',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mostviewpage',
            name='year',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
