# Generated by Django 4.0 on 2024-08-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toprofile_api', '0006_remove_mostviewpage_name_mostviewpage_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostviewpage',
            name='year',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
