# Generated by Django 4.0 on 2024-08-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toprofile_api', '0007_alter_mostviewpage_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogView', to='toprofile_api.blog')),
            ],
        ),
    ]
