# Generated by Django 4.0 on 2024-08-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toprofile_api', '0009_alter_blogviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertyImages', to='toprofile_api.propertylisting'),
        ),
    ]
