# Generated by Django 4.0 on 2024-08-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toprofile_api', '0010_alter_imageasset_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
